version: "3.9"

services:
  api:
    build: .
    container_name: lbc_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - lbc_net

  mysql:
    image: mysql:8
    container_name: lbc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lbc
      MYSQL_USER: lbc_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - lbc_net

networks:
  lbc_net:

volumes:
  mysql_data:
